spring:
  application:
    name: produto-market
  datasource:
    username: nbbdmeoc
    url: jdbc:postgresql://babar.db.elephantsql.com/nbbdmeoc
    password: 3hAqpsbwYZghTIWOqX9ptjnLTnrOPGZ4
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true '
    show-sql: 'false'
    hibernate:
      ddl-auto: none
  database:
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgresql
