spring:
  application:
    name: produto-market
  datasource:
    username: ktkhwwsu
    url: jdbc:postgresql://kesavan.db.elephantsql.com/ktkhwwsu
    password: 4J5V6VDI31ZXcHhbNzuvl4_vsnWbApJ-
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true '
    show-sql: 'false'
    hibernate:
      ddl-auto: update
  database:
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgresql
